CREATE TABLE [dbo].[SS_NGDZRWGS](
	[id] [dbo].[ut_xh12] IDENTITY(1,1) NOT NULL,
	[name] [dbo].[ut_mc16] NOT NULL,
	[py] [dbo].[ut_py] NULL,
	[wb] [dbo].[ut_py] NULL,
	[jlzt] [SMALLINT] NOT NULL,
 CONSTRAINT [PK_SS_NGDZRWGS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

