alter  table SS_SSDJK add blbb    ut_mc16 NULL
alter  table SS_SSDJK add gd        ut_bz   NULL
alter  table SS_SSDJK add ssylg     ut_mc16 NULL
alter  table SS_SSDJK add jbss      ut_mc16 NULL
alter  table SS_SSDJK add jrss      ut_mc16 NULL
alter  table SS_SSDJK add qcgj      ut_bz   NULL
alter  table SS_SSDJK add sxgj      ut_mc32 NULL
alter  table SS_SSDJK add ngdzrw    ut_mc16 NULL
alter  table SS_SSDJK add ngdzrwgs  ut_mc16 NULL
alter  table SS_SSDJK add sqdn      ut_mc16 NULL
alter  table SS_SSDJK add kjywdm    ut_dm12 NULL
alter  table SS_SSDJK add jl1       ut_mc16 NULL
alter  table SS_SSDJK add jldw1     ut_mc16 NULL
alter  table SS_SSDJK add sqyysj    ut_mc16 NULL
alter  table SS_SSDJK add sqyycj    ut_mc16 NULL
alter  table SS_SSDJK add zjkjywdm  ut_dm12 NULL
alter  table SS_SSDJK add zjkjywmc  ut_mc64 NULL
alter  table SS_SSDJK add jl2       ut_mc16 NULL
alter  table SS_SSDJK add jldw2     ut_mc16 NULL
alter  table SS_SSDJK add szyysj    ut_mc16 NULL
alter  table SS_SSDJK add szyycj    ut_mc16 NULL
alter  table SS_SSDJK add sjyysj    ut_rq16 NULL
alter  table SS_SSDJK add qczrw1    ut_mc64 NULL
alter  table SS_SSDJK add qczrwsl   ut_mc16 NULL
alter  table SS_SSDJK add crbmc2    ut_mc32 NULL
alter  table SS_SSDJK add kkss      ut_mc16 NULL
alter  table SS_SSDJK add yyzt      ut_mc16 NULL
alter  table SS_SSDJK add wqzj      ut_mc16 NULL
alter  table SS_SSDJK add xssdm6    ut_xmdm NULL
alter  table SS_SSDJK add xssdm7    ut_xmdm NULL
alter  table SS_SSDJK add xssdm8    ut_xmdm NULL
alter  table SS_SSDJK add xssdm9    ut_xmdm NULL
alter  table SS_SSDJK add xssdm10   ut_xmdm NULL
alter  table SS_SSDJK add xssdm11   ut_xmdm NULL
alter  table SS_SSDJK add xssdm12   ut_xmdm NULL
alter  table SS_SSDJK add xssdm13   ut_xmdm NULL
alter  table SS_SSDJK add xssdm14   ut_xmdm NULL
alter  table SS_SSDJK add xssdm15   ut_xmdm NULL
alter  table SS_SSDJK add xssmc6    ut_ssmc NULL
alter  table SS_SSDJK add xssmc7    ut_ssmc NULL
alter  table SS_SSDJK add xssmc8    ut_ssmc NULL
alter  table SS_SSDJK add xssmc9    ut_ssmc NULL
alter  table SS_SSDJK add xssmc10   ut_ssmc NULL
alter  table SS_SSDJK add xssmc11   ut_ssmc NULL
alter  table SS_SSDJK add xssmc12   ut_ssmc NULL
alter  table SS_SSDJK add xssmc13   ut_ssmc NULL
alter  table SS_SSDJK add xssmc14   ut_ssmc NULL
alter  table SS_SSDJK add xssmc15   ut_ssmc NULL
alter  table SS_SSDJK add sszc1     varchar(1) NULL
alter  table SS_SSDJK add sszc2     varchar(1) NULL
alter  table SS_SSDJK add sszc3     varchar(1) NULL
alter  table SS_SSDJK add sszc4     varchar(1) NULL
alter  table SS_SSDJK add sszc5     varchar(1) NULL
alter  table SS_SSDJK add sszc6     varchar(1) NULL
alter  table SS_SSDJK add sszc7     varchar(1) NULL
alter  table SS_SSDJK add sszc8     varchar(1) NULL
alter  table SS_SSDJK add sszc9     varchar(1) NULL
alter  table SS_SSDJK add sszc10    varchar(1) NULL
alter  table SS_SSDJK add sszc11    varchar(1) NULL
alter  table SS_SSDJK add sszc12    varchar(1) NULL
alter  table SS_SSDJK add sszc13    varchar(1) NULL
alter  table SS_SSDJK add sszc14    varchar(1) NULL
alter  table SS_SSDJK add sszc15    varchar(1) NULL
alter  table SS_SSDJK add ssys      ut_mc64 NULL
alter  table SS_SSDJK add sshs      ut_mc64 NULL
alter  table SS_SSDJK add sslrczyxm ut_mc16 NULL
alter  table SS_SSDJK add sfcs      ut_mc16 NULL
alter  table SS_SSDJK add hzzy      ut_mc16 NULL
alter  table SS_SSDJK add ssfy      ut_mc16 NULL
alter  table SS_SSDJK add qkqk      ut_mc16 NULL
alter  table SS_SSDJK add ywzqtys   ut_mc16 NULL
alter  table SS_SSDJK add ywsqxj    ut_mc16 NULL
alter  table SS_SSDJK add ywssbwbs  ut_mc16 NULL
alter  table SS_SSDJK add ssbwsfzq  ut_mc16 NULL
alter  table SS_SSDJK add sfhg      ut_mc16 NULL
alter  table SS_SSDJK add jcr       ut_mc16 NULL
alter  table SS_SSDJK add xssdm2    ut_ssdm NULL
alter  table SS_SSDJK add xssmc2    ut_ssmc NULL
alter  table SS_SSDJK add sqfs      ut_mc16 NULL
alter  table SS_SSDJK add aqjc      ut_mc16 NULL
ALTER TABLE [dbo].[SS_SSDJK] ADD [qcfs2] [VARCHAR](4) NULL
ALTER TABLE [dbo].[SS_SSDJK] ADD [jjss] [VARCHAR](32) NULL
ALTER TABLE [dbo].[SS_SSDJK] ADD [xqss] [VARCHAR](32) NULL
ALTER TABLE [dbo].[SS_SSDJK_FZ] ADD [jjss] [VARCHAR](32) NULL
ALTER TABLE [dbo].[SS_SSDJK_FZ] ADD [xqss] [VARCHAR](32) NULL

alter  table SS_SSDJK add sqfs      ut_mc16 NULL
alter  table SS_SSDJK add aqjc      ut_mc16 NULL
alter  table SS_SSDJK add qcfs2      VARCHAR(4)NULL
ALTER TABLE [dbo].[SS_SSDJK] ADD [jjss] [VARCHAR](32) NULL
ALTER TABLE [dbo].[SS_SSDJK] ADD [xqss] [VARCHAR](32) NULL
ALTER TABLE [dbo].[SS_SSDJK_FZ] ADD [jjss] [VARCHAR](32) NULL
ALTER TABLE [dbo].[SS_SSDJK_FZ] ADD [xqss] [VARCHAR](32) NULL