IF OBJECT_ID('utf_his5_Getzlxmmx','TF') IS NOT NULL
DROP FUNCTION utf_his5_Getzlxmmx
GO

CREATE FUNCTION utf_his5_Getzlxmmx
(
	@GHXH INT,
	@YSDM u5_czyh
)
RETURNS @ZLXXMX TABLE
(
	YPMC u5_mc64,
	YPSL u5_sl10,
	YPDW u5_unit,
	YPJE u5_sl10,
	ZXKS u5_mc32
)
AS

BEGIN
	DECLARE @YPMC u5_mc64,
			@YPSL u5_sl10,
			@YPDW u5_unit,
			@YPJE u5_sl10,
			@ZXKS u5_mc32

	DECLARE CS_YPMCCL CURSOR FOR
	SELECT b.YPMC,CONVERT(NUMERIC(12,2),b.YPSL/b.YPXS),b.YPDW,CONVERT(NUMERIC(12,2),b.YLSJ*b.YPSL/b.YPXS),a.YFMC FROM dbo.OUTP_ORDER a (NOLOCK)
		INNER JOIN dbo.OUTP_ORDERITEM b (NOLOCK) ON a.XH=b.CFXH
	WHERE a.GHXH=@GHXH AND YSDM=@YSDM
			AND a.CFLX=5 AND a.JLZT=0
	OPEN CS_YPMCCL
	FETCH FROM CS_YPMCCL INTO @YPMC,@YPSL,@YPDW,@YPJE,@ZXKS
	WHILE @@FETCH_STATUS=0
	BEGIN
		IF LEN(@YPMC)>15
		BEGIN
			INSERT INTO @ZLXXMX (YPMC, YPSL, YPDW, YPJE, ZXKS )
			VALUES (SUBSTRING(@YPMC,1,15),@YPSL,@YPDW,@YPJE,@ZXKS)

			INSERT INTO @ZLXXMX (YPMC, YPSL, YPDW, YPJE, ZXKS )
			VALUES (SUBSTRING(@YPMC,16,LEN(@YPMC)),0,'',0,'')
		END
		ELSE
			INSERT INTO @ZLXXMX (YPMC, YPSL, YPDW, YPJE, ZXKS )
			VALUES (SUBSTRING(@YPMC,1,15),@YPSL,@YPDW,@YPJE,@ZXKS)      

		FETCH FROM CS_YPMCCL INTO @YPMC,@YPSL,@YPDW,@YPJE,@ZXKS
	END
	CLOSE CS_YPMCCL
	DEALLOCATE CS_YPMCCL

	RETURN
END

